version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "${APP_PORT:-9808}:${APP_PORT:-9808}"
    depends_on:
      - redis
    environment:
      - PORT=${APP_PORT:-9808}
      - BASE_URL=${APP_BASE_URL:-http://localhost:9808}
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
volumes:
  postgres:
