apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: us-west2-docker.pkg.dev/onyx-codex-415020/url-shortener/url-shortener-amd64:latest-v10
          ports:
            - containerPort: 8080
          env:
            - name: EXTERNAL_URL
              value: "https://34.94.19.218"  # Change to 'https'
          imagePullPolicy: Always

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-shortener-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - "34.94.19.218.nip.io"
    secretName: my-tls-secret
  rules:
  - host: "34.94.19.218.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: url-shortener-service
            port:
              number: 8080
